### ISSUE TITLE
Still doesn't seem to work

### ISSUE THREAD

**Issue by reasonablefaith** [Foxei/reDump#1]
Hello,

I tried running it using the directions you provided, but it doesn't seem to be working for me. Any suggestions? Here's the output from when I run it:

> ./reStream.sh
[SSH] true
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
[SSH] cat /sys/devices/soc0/machine
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
[SSH] pidof xochitl
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
xochitl's PID: 215
[SSH] grep -C1 '/dev/fb0' /proc/215/maps | tail -n1 | sed 's/-.*$//'
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
framebuffer is at 0x1924165632
[SSH] [ -f /opt/bin/lz4 ]
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
[SSH] [ -f ~/lz4 ]
Enter passphrase for key '/home/emerald/.ssh/id_rsa': 
[SSH] while /home/root/reDump -p 215 -b 1924165632 -s 8 -c 2628288; do true; done | $HOME/lz4
ffplay version 4.3.1-4ubuntu1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 10 (Ubuntu 10.2.0-9ubuntu2)
  configuration: --prefix=/usr --extra-version=4ubuntu1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-nvenc --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0   
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, bitrate: 525657 kb/s
    Stream #0:0: Video: rawvideo (Y800 / 0x30303859), gray, 1872x1404, 525657 kb/s, 25 tbr, 25 tbn, 25 tbc

**Comment by Foxei** [comment]
Hello @reasonablefaith,
can you describe what exactly is not working? Are you getting no output window, a black screen or bunch of garbage on the screen?  What reMarkable software version are you running on?

The terminal output looks good as well as the parameters passed to reDump.

**Comment by reasonablefaith** [comment]
actually, after restarting my computer it seems to work! Not sure what it
was. It wasn't opening a window for reMarkable at all.

**Comment by Foxei** [comment]
And can you verify that the reDump executables is working?
Just SSH onto the reMarkable and try. ‘./reDump —version’ in the root home directory.

**Comment by Foxei** [comment]
Nice, problem solved by turning it off and on again. Classic. 😄
